#!/bin/bash
# Use this script to compile your .cc files in dependency order.
# Assumes existence of syslibs.txt contains a list of any system 
# libraries imported.

# Arguments:
#   $1 = name of file containing list of .cc files
#   $2 = name of the output file

cxx="g++-14"
cxxflags="-std=c++20 -fmodules-ts -Wall -g"
gcmsyspath="gcm.cache/usr/local/gcc-14.2.0/include/c++/14.2.0"

if [ $# -lt 1 ]; then
  echo "Usage:  $0 list-filename [output-name]" 1>&2
  exit 1
fi

if [ -e "syslibs.txt" ]; then
  for x in $(cat "syslibs.txt"); do
    if [ ! -e "${gcmsyspath}/${x}.gcm" ]; then
      echo $cxx $cxxflags -x c++-system-header -c $x
      $cxx $cxxflags -x c++-system-header -c $x
    fi
  done
fi

if [ $# -eq 2 ]; then
  name="-o $2"
fi

for x in $(cat $1); do
  echo $cxx $cxxflags -c $x
  $cxx $cxxflags -c $x
done

echo $cxx *.o $name
$cxx *.o $name

